
package com.smona.base.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "DownloadFile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DownloadFile", targetNamespace = "http://webservice.com/", className = "com.webservice.DownloadFile")
    @ResponseWrapper(localName = "DownloadFileResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.DownloadFileResponse")
    @Action(input = "http://webservice.com/WebServiceImpl/DownloadFileRequest", output = "http://webservice.com/WebServiceImpl/DownloadFileResponse")
    public byte[] downloadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VreBusiness")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "VreBusiness", targetNamespace = "http://webservice.com/", className = "com.webservice.VreBusiness")
    @ResponseWrapper(localName = "VreBusinessResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.VreBusinessResponse")
    @Action(input = "http://webservice.com/WebServiceImpl/VreBusinessRequest", output = "http://webservice.com/WebServiceImpl/VreBusinessResponse")
    public String vreBusiness(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
